baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Quadromático"
[params]
description = "Sistema planejador de Quadros de Horários."
[[params.social]]
icon = "envelope-o"
title = "email"
url = "mailto:gabriel.yamasita@hotmail.com"
[[params.social]]
icon = "gitlab"
title = "gitlab"
url = "http://trab.dc.unifil.br/gitlab/npi/quadromatico"
[[params.social]]
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
icon = "facebook"
title = "facebook"
url = "https://www.facebook.com/gabriel.yamasita"
