baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Quadromático"
[params]
	description = "Sistema planejador de Quadros de Horários."

[[params.social]]
	title = "email"
	icon = "envelope-o"
	url = "mailto:gabriel.yamasita@hotmail.com"
[[params.social]]
	title = "github"
	icon = "github"
	url = "https://github.com/GabrielYamasita/"
[[params.social]]
	title = "facebook"
	icon = "facebook"
	url = "https://www.facebook.com/gabriel.yamasita"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
